# Generated by Django 4.1.5 on 2023-01-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0003_remove_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
