# Generated by Django 4.1.5 on 2023-01-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0005_product_image_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="countInStock",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="numReviews",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
