# Generated by Django 4.1.5 on 2023-01-23 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0007_remove_product_brand_remove_product_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="createdAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
