# Generated by Django 4.1.5 on 2023-01-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0009_alter_product_createdat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="id",
        ),
        migrations.AddField(
            model_name="product",
            name="_id",
            field=models.AutoField(
                default=False, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
