# Generated by Django 4.1.5 on 2023-01-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("air_one", "0002_plane_route"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["name"]},
        ),
    ]
